routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
})->name('landing');

//Auth
Auth::routes();
Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', [
        'uses' => 'HomeController@index',
        'middleware' => 'roles',
        'roles' => ['Super Admin','Normal Admin']

    ])->name('super_admin_home');

    Route::get('/normal', function () {
        return view('normal');
    });
});

//Admin
Route::get('users/active', 'AdminController@app_users')->name('users');
Route::get('users', 'AdminController@active_users')->name('active_users');
Route::get('admins','AdminController@admins')->name('admins');
Route::get('admin/add','AdminController@add_admin_form')->name('add_admin_form');
Route::get('admin/{admin_id}/deactivate','AdminController@deactivate_admin')->name('deactivate_admin');
Route::get('admin/{admin_id}/activate','AdminController@activate_admin')->name('activate_admin');
Route::post('admin/add','AdminController@create_admin')->name('create_admin');
Route::get('user/{id}/details','AdminController@user_details')->name('user_details');
Route::get('user/{id}/profile','AdminController@user_profile')->name('user_profile');
Route::get('user/{id}/loans','AdminController@user_loans')->name('user_loans');
Route::get('user/{id}/repayments','AdminController@user_repayments')->name('user_repayments');
Route::get('users/blocked','AdminController@blocked_users')->name('blocked_users');
Route::get('users/flagged','AdminController@flagged_users')->name('flagged_users');
Route::get('users/{user_id}/reset/account','AdminController@flagged_user_reset')->name('reset_flagged_users');
Route::get('users/{user_id}/edit/profile','AdminController@edit_user_profile')->name('edit_user_profile');
Route::post('users/{user_id}/update/details','AdminController@flagged_user_update')->name('flagged_user_update');
Route::get('users/{user_id}/block','AdminController@block_user')->name('block_user');
Route::get('users/{user_id}/unblock','AdminController@unblock_user')->name('unblock_user');
Route::get('loan/request/{request_id}/accept','LoanController@accept_request')->name('admin_accept_loan_request');
Route::get('loan/request/{request_id}/reject','LoanController@reject_request')->name('admin_reject_loan_request');
Route::get('loan/requests','LoanController@loan_requests')->name('loan_requests');
Route::get('unverified/users','AdminVerificationController@unverified_users')->name('unverified_users');
Route::get('verify/user/{user_id}','AdminVerificationController@verify_user')->name('verify_user');
Route::get('reject/user/{user_id}','AdminVerificationController@reject_user')->name('reject_user');

//users with bad debt
Route::get('users/bad_debts','AdminController@app_users_with_bad_debt')->name('bad_debt_users');

//pass resets

//Route::get('admin/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
//Route::post('admin/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
//Route::get('admin/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
//Route::post('admin/reset', 'Auth\ResetPasswordController@reset');


//loans
Route::get('loans/all', 'LoanController@index')->name('loans');
Route::get('loans/active', 'LoanController@active_loans')->name('loans_active');
Route::get('loans/defaulted', 'LoanController@defaulted_loans')->name('loans_defaulted');
Route::get('loans/cleared', 'LoanController@cleared_loans')->name('loans_cleared');
Route::get('loan_limits', 'LoanController@loan_limits')->name('loan_limits');
Route::get('admin_set_loan_limits','LoanController@admin_set_limits')->name('admin_set_limits');
Route::get('system_set_loan_limits','LoanController@system_set_limits')->name('system_set_limits');
Route::get('create/loan_limit','LoanController@create_limit')->name('loan_limit_create_form');
Route::post('create/loan_limit','LoanController@store_limit')->name('loan_limit_store');
Route::get('set/user/{id}/limit','LoanController@set_loan_limit_form')->name('set_loan_limit_form');
Route::post('set/user/{id}/limit','LoanController@set_loan_limit')->name('set_loan_limit');
Route::get('loans/payments','LoanController@payments')->name('loan_payments');
Route::get('admin_set/loan_limits/{id}/reset','LoanController@reset_admin_set_limit')->name('loan_limit_reset');
Route::get('admin_set/loan_limits/{id}/activate','LoanController@activate_admin_set_limit')->name('loan_limit_activate');
Route::get('admin/set/limit/{id}/edit/form','LoanController@limit_update_form')->name('limit_update_form');
Route::post('admin/set/limit/{id}/edit/form','LoanController@limit_update')->name('limit_update');
Route::get('all/users','AdminController@select_users_table')->name('select_users_table');

//loan bad debt
Route::get('bad_debt/id/{id}/val/{val}','LoanController@set_or_unset_bad_debt')->name('bad_debt');

//countries
Route::get('countries',"AdminController@countries")->name('countries');
Route::get('create/country/form',"AdminController@create_contry")->name('country_form');
Route::post('create/country',"AdminController@store_country")->name('country_store');
Route::get('country/{country_id}/edit','AdminController@edit_country')->name('country_edit');
Route::post('country/{country_id}/update','AdminController@update_country')->name('country_update');

//regions
Route::get('country/{country_id}/details','AdminController@country_details')->name('country_details');
Route::get('create/region/{id}/form',"AdminController@create_region")->name('region_form');
Route::post('create/region',"AdminController@store_region")->name('region_store');
Route::get('edit/region/{id}/form','AdminController@edit_region')->name('region_edit');
Route::post('update/region/{id}','AdminController@update_region')->name('region_update');





//reminders
Route::get('reminders', 'AdminController@reminders')->name('reminders');

//repayments
Route::get('loan/{id}/repayments','AdminController@repayments')->name('repayments');


//Route::get('/confirmation','MpesaController@confirmation')->name('mpesa_confirmation');
//Route::get('/validation','MpesaController@validation')->name('mpesa_validation');

//Route::get('/admin/login/form',[
//    'uses'=>'AdminAuth/LoginController@showLoginForm'
//])->name('admin_login_form');
//Route::post('/admin/login',['uses'=>'AdminAuth/LoginController@login'])->name('admin_login');
//Route::post('/admin/logout',['uses'=>'AdminAuth/LoginController@logout'])->name('admin_logout');

Route::get('test','AdminController@test')->name('test');


/*
|--------------------------------------------------------------------------
| Faq Routes
|--------------------------------------------------------------------------
*/

Route::prefix('faq')->group(function (){
    Route::get('/list','FaqController@index')->name('faq-all');
    Route::get('/create','FaqController@create')->name('faq-create');
    Route::post('/store','FaqController@store')->name('faq-store');
    Route::get('/edit/{id}','FaqController@edit')->name('faq-edit');
    Route::get('/show/{id}', 'FaqController@show')->name('faq-show');
    Route::post('/update/{id}','FaqController@update')->name('faq-update');
    Route::get('/delete/{id}','FaqController@destroy')->name('faq-destroy');
});

/*
|--------------------------------------------------------------------------
| End Faq Routes
|--------------------------------------------------------------------------
*/

/*
|--------------------------------------------------------------------------
| Repayment Cycles Routes
|--------------------------------------------------------------------------
*/

Route::prefix('repaymentcycle')->group(function (){
    Route::get('/list','RepayCycleController@index')->name('repaymentcycles');
    Route::get('/create','RepayCycleController@create')->name('repaymentcycle-create');
    Route::post('/store','RepayCycleController@store')->name('repaymentcycle-store');
    Route::get('/edit/{id}','RepayCycleController@edit')->name('repaymentcycle-edit');
    Route::post('/update/{id}','RepayCycleController@update')->name('repaymentcycle-update');
    Route::get('/delete/{id}','RepayCycleController@destroy')->name('repaymentcycle-destroy');
});

Route::prefix('code')->group(function (){
    Route::get('/list','CodeController@index')->name('code');
    Route::get('/create','CodeController@create')->name('code-create');
    Route::post('/store','CodeController@store')->name('code-store');
});

/*
|--------------------------------------------------------------------------
| End Repayment Cycles Routes
|--------------------------------------------------------------------------
*/

/*
|--------------------------------------------------------------------------
| App Minimum Version Routes
|--------------------------------------------------------------------------
*/

Route::prefix('minimumappversion')->group(function (){
    Route::get('/list','MinimumAppVersionController@index')->name('minimumversions');
    Route::get('/create','MinimumAppVersionController@create')->name('minimumversion-create');
    Route::post('/store','MinimumAppVersionController@store')->name('minimumversion-store');
    Route::get('/edit/{id}','MinimumAppVersionController@edit')->name('minimumversion-edit');
    Route::post('/update/{id}','MinimumAppVersionController@update')->name('minimumversion-update');
    Route::get('/delete/{id}','MinimumAppVersionController@destroy')->name('minimumversion-destroy');
});

/*
|--------------------------------------------------------------------------
| End App Minimum Version Routes

app/AppUser.php
<?php

namespace App;


use Laravel\Passport\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class AppUser extends Authenticatable
{
    use HasApiTokens, Notifiable;

    const ACTIVE_LOAN = 1;
    const CLEARED_LOAN = 2;
    const DEFAULTED_LOAN = 3;
    const ACTIVE_USER = 1;
    const BLOCKED_USER = 2;


//    protected $table="app_users";
//
//    public function findForPassport($username) {
//        return $this->where('phone_number', $username)->first();
//    }

    protected $fillable = [

        'first_name', 'second_name', 'surname', 'region_id', 'phone_number', 'pin', 'occupation', 'id_number', 'date_of_birth', 'email', 'status'

    ];

    protected $hidden = [
        'pin', 'remember_token',
    ];

    public function loans()
    {
        return $this->hasMany('App\Loan', 'user_id');
    }

    public function active_loan()
    {
        return $this->loans()->where('loan_status', '=', $this::ACTIVE_LOAN);
    }

    public function defaulted_loan()
    {
        return $this->loans()->where('loan_status', '=', $this::DEFAULTED_LOAN);
    }
    public function cleared_loan()
    {
        return $this->loans()->where('loan_status', '=', $this::CLEARED_LOAN);
    }

    public function getAdminVerificationAttribute()
    {

        $verification = AdminUserVerification::where('app_user_id',$this->id)->first();

        return $verification;

    }

    public function getRegionAttribute()
    {

        $region = Region::where('id',$this->region_id)->first();

        return $region->name;

    }

    public function getGenderAttribute()
    {
        $details = MetropolDetail::where('user_id',$this->id)->first();

        return $details->gender;
    }
}

app/User.php
<?php

namespace App;

use App\Notifications\PassResetNotification;
use Illuminate\Contracts\Auth\CanResetPassword;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements CanResetPassword
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name','last_name', 'email', 'password','status'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new PassResetNotification($token));
    }

    public function roles()
    {
        return $this->belongsToMany('App\Role', 'user_role', 'user_id', 'role_id');
    }
    public function hasAnyRole($roles)
    {
        if (is_array($roles)) {
            foreach ($roles as $role) {
                if ($this->hasRole($role)) {
                    return true;
                }
            }
        } else {
            if ($this->hasRole($roles)) {
                return true;
            }
        }
        return false;
    }

    public function hasRole($role)
    {
        if ($this->roles()->where('name', $role)->first()) {
            return true;
        }
        return false;
    }

//    public function getRole() {
//        if ($this->hasRole('Super Admin')){
//            return 'Super Admin';
//        } elseif ($this->hasRole('Normal Admin')) {
//            return 'Normal Admin';
//        }
//    }

//    public function checkRole(){
//        if ($this->hasRole('Super Admin')){
//            return 'Super Admin';
//        }elseif ($this->hasRole('Normal Admin')){
//            return 'Normal Admin';
//        }
//    }


}

resources/views/users/active.blade.php
@extends('layouts.dash_side_top')
@section('styles')
    <link rel="stylesheet" type="text/css" href="https://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/css/jquery.dataTables.css">
@endsection
@section('content')
    <div class="row">
        <!-- Page Header -->
        <div class="col-lg-12">
            <h1 class="headers">Active Users</h1>
        </div>
        <!--End Page Header -->
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="stat-bars">
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover" id="example">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>Region</th>
                                <th>Phone</th>
                                <th>Loan Limit</th>
                                <th>Details</th>
                            </tr>
                            </thead>
                            @foreach($active_users as $app_user)
                                <tr>
                                    <td>{{$app_user->first_name}} {{$app_user->second_name}} {{$app_user->surname}}</td>
                                    <td>{{$app_user->region}}</td>
                                    <td>{{$app_user->phone_number}}</td>
                                    <td>KSh. {{\App\Http\Traits\UniversalMethods::getLoanLimit($app_user->id)}}</td>
                                    <td><a href="{{route('user_profile',['id'=>$app_user->id])}}">More Details</a></td>
                                </tr>
                            @endforeach
                            <tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script type="text/javascript" charset="utf8" src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.2.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/jquery.dataTables.min.js"></script>
    <script>
        $.noConflict();
        jQuery( document ).ready(function( $ ) {
            $('#example').DataTable();
        });
    </script>
@endsection

resources/views/users/all_users.blade.php
@extends('layouts.dash_side_top')
@section('styles')
    <link rel="stylesheet" type="text/css"
          href="{{URL::to('https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css')}}">
    <link rel="stylesheet" type="text/css"
          href="{{URL::to('https://cdn.datatables.net/buttons/1.5.2/css/buttons.dataTables.min.css')}}">
@endsection
@section('content')
    <div class="row">
        <!-- Page Header -->
        <div class="col-lg-12">
            <h1 class="headers">Users</h1>
        </div>
        <!--End Page Header -->
    </div>
    <div class="row offset-1">
        <div class="col-lg-2">
            <div class="in-navs">
                <a href="{{route('unverified_users')}}"  class="btn {{url()->current()==route('unverified_users')? "active": ""}}"><i
                            class="fa fa-thumbs-up"></i>Unverified Users</a>
            </div>
        </div>
        <div class="col-lg-2">
            <div class="in-navs">
                <a href="{{route('users')}}" class="btn {{url()->current()==route('users')? "active": ""}}"><i
                            class="fa fa-thumbs-up"></i>Active Users</a>
            </div>
        </div>
        <div class="col-lg-2">
            <div class="in-navs">
                <a href="{{route('blocked_users')}}" class="btn {{url()->current()==route('blocked_users')? "active": ""}}"><i class="fa fa-thumbs-down"></i>Blocked Users</a>
            </div>
        </div>
        <div class="col-lg-2">
            <div class="in-navs">
                <a href="{{route('flagged_users')}}" class="btn {{url()->current()==route('flagged_users')? "active": ""}}"><i class="fa fa-ban"></i>Flagged Accounts</a>
            </div>
        </div>
        <div class="col-lg-2">
            <div class="in-navs">
                <a href="{{route('bad_debt_users')}}" class="btn {{url()->current()==route('bad_debt_users')? "active": ""}}"><i class="fa fa-ban"></i>Bad Debts</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="stat-bars">
                <div class="panel-body">
                    <div class="table-responsive table-customize">
                        <table class="table table-bordered table-hover" id="example">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>Region</th>
                                <th>Phone</th>
                                <th>Loan Limit</th>
                                {{--<th>Profile</th>--}}
                                <th>Loan Status</th>
                                <th>Block</th>
                            </tr>
                            </thead>
                            @foreach($app_users as $app_user)
                                <tr>
                                    <td>
                                        <a href="{{route('user_profile',['id'=>$app_user->id])}}">{{$app_user->first_name}} {{$app_user->second_name}} {{$app_user->surname}}</a>
                                    </td>
                                    <td>{{$app_user->region}}</td>
                                    <td>{{$app_user->phone_number}}</td>
                                    <td>KSh. {{\App\Http\Traits\UniversalMethods::getLoanLimit($app_user->id)}}</td>
                                    {{--                                    <td><a href="{{route('user_profile',['id'=>$app_user->id])}}">View Profile</a></td>--}}
                                    @if(\App\Http\Traits\UniversalMethods::hasActiveLoan($app_user->id))
                                        <td style="color: #1f6fb2">Active</td>
                                    @else
                                        @if($app_user->loans->where('loan_status',4)->first() != null)
                                            <td style="color: #E55025">Has a Bad Debt</td>
                                        @else
                                            <td style="color: #012B43">Inactive</td>
                                        @endif
                                    @endif

                                    <td><a href="{{route('block_user',['user_id'=>$app_user->id])}}"
                                           class="btn btn-custom">Block</a></td>
                                </tr>
                            @endforeach
                            <tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    {{--    <script type="text/javascript" charset="utf8" src="{{URL::to('https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.2.min.js')}}}"></script>--}}
    {{--<script type="text/javascript" charset="utf8" src="{{URL::to('https://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/jquery.dataTables.min.js')}}"></script>--}}

    <script type="text/javascript" charset="utf8"
            src="{{URL::to('https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js')}}"></script>
    <script type="text/javascript" charset="utf8"
            src="{{URL::to('https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js')}}"></script>
    <script type="text/javascript" charset="utf8"
            src="{{URL::to('https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js')}}"></script>
    <script type="text/javascript" charset="utf8"
            src="{{URL::to('https://cdn.datatables.net/buttons/1.5.2/js/buttons.flash.min.js')}}"></script>
    <script type="text/javascript" charset="utf8"
            src="{{URL::to('https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js')}}"></script>
    <script type="text/javascript" charset="utf8"
            src="{{URL::to('https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js')}}"></script>
    <script type="text/javascript" charset="utf8"
            src="{{URL::to('https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js')}}"></script>
    <script type="text/javascript" charset="utf8"
            src="{{URL::to('https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js')}}"></script>
    <script type="text/javascript" charset="utf8"
            src="{{URL::to('https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js')}}"></script>

    <script>
        $.noConflict();
        jQuery(document).ready(function ($) {
            $('#example').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'excel'
                ]
            });
        });
    </script>
@endsection

resources/views/users/unverified.blade.php
@extends('layouts.dash_side_top')
@section('styles')
    <link rel="stylesheet" type="text/css"
          href="{{URL::to('https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css')}}">
    <link rel="stylesheet" type="text/css"
          href="{{URL::to('https://cdn.datatables.net/buttons/1.5.2/css/buttons.dataTables.min.css')}}">
@endsection
@section('content')
    <div class="row">
        <!-- Page Header -->
        <div class="col-lg-12">
            <h1 class="headers">Users</h1>
        </div>
        <!--End Page Header -->
    </div>
    <div class="row offset-1">
        <div class="col-lg-2">
            <div class="in-navs">
                <a href="{{route('unverified_users')}}"  class="btn {{url()->current()==route('unverified_users')? "active": ""}}"><i
                        class="fa fa-thumbs-up"></i>Unverified Users</a>
            </div>
        </div>
        <div class="col-lg-2">
            <div class="in-navs">
                <a href="{{route('users')}}" class="btn {{url()->current()==route('users')? "active": ""}}"><i
                        class="fa fa-thumbs-up"></i>Active Users</a>
            </div>
        </div>
        <div class="col-lg-2">
            <div class="in-navs">
                <a href="{{route('blocked_users')}}" class="btn {{url()->current()==route('blocked_users')? "active": ""}}"><i class="fa fa-thumbs-down"></i>Blocked Users</a>
            </div>
        </div>
        <div class="col-lg-2">
            <div class="in-navs">
                <a href="{{route('flagged_users')}}" class="btn {{url()->current()==route('flagged_users')? "active": ""}}"><i class="fa fa-ban"></i>Flagged Accounts</a>
            </div>
        </div>
        <div class="col-lg-2">
            <div class="in-navs">
                <a href="{{route('bad_debt_users')}}" class="btn {{url()->current()==route('bad_debt_users')? "active": ""}}"><i class="fa fa-ban"></i>Bad Debts</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="stat-bars">
                <div class="panel-body">
                    <div class="table-responsive table-customize">
                        <table class="table table-bordered table-hover" id="example">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>Region</th>
                                <th>Phone</th>
                                <th>Loan Limit</th>
                                <th>Loan Status</th>
                                <th>Verify</th>
                                <th>Reject</th>
                            </tr>
                            </thead>
                            @foreach($app_users as $app_user)
                                @if($app_user->admin_verification == null || $app_user->admin_verification->admin_verification_status == 1 || $app_user->admin_verification->admin_verification_status == 3)
                                <tr>
                                    <td>
                                        <a href="{{route('user_profile',['id'=>$app_user->id])}}">{{$app_user->first_name}} {{$app_user->second_name}} {{$app_user->surname}}</a>
                                    </td>
                                    <td>{{$app_user->region}}</td>
                                    <td>{{$app_user->phone_number}}</td>
                                    <td>KSh. {{\App\Http\Traits\UniversalMethods::getLoanLimit($app_user->id)}}</td>
                                    {{--                                    <td><a href="{{route('user_profile',['id'=>$app_user->id])}}">View Profile</a></td>--}}
                                    @if(\App\Http\Traits\UniversalMethods::hasActiveLoan($app_user->id))
                                        <td style="color: #1f6fb2">Active</td>
                                    @else
                                        @if($app_user->loans->where('loan_status',4)->first() != null)
                                            <td style="color: #E55025">Has a Bad Debt</td>
                                        @else
                                            <td style="color: #012B43">Inactive</td>
                                        @endif
                                    @endif

                                    @if($app_user->admin_verification == null || $app_user->admin_verification->admin_verification_status == 1 )

                                        <td><a href="{{route('verify_user',['user_id'=>$app_user->id])}}"
                                               class="btn btn-custom">Verify</a></td>
                                        <td><a href="{{route('reject_user',['user_id'=>$app_user->id])}}"
                                               class="btn btn-custom">Reject</a></td>

                                        @else
                                        <td style="color: red">Rejected</td>
                                        <td style="color: red">Rejected</td>
                                        @endif
                                </tr>
                                @endif
                            @endforeach
                            <tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    {{--    <script type="text/javascript" charset="utf8" src="{{URL::to('https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.2.min.js')}}}"></script>--}}
    {{--<script type="text/javascript" charset="utf8" src="{{URL::to('https://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/jquery.dataTables.min.js')}}"></script>--}}

    <script type="text/javascript" charset="utf8"
            src="{{URL::to('https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js')}}"></script>
    <script type="text/javascript" charset="utf8"
            src="{{URL::to('https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js')}}"></script>
    <script type="text/javascript" charset="utf8"
            src="{{URL::to('https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js')}}"></script>
    <script type="text/javascript" charset="utf8"
            src="{{URL::to('https://cdn.datatables.net/buttons/1.5.2/js/buttons.flash.min.js')}}"></script>
    <script type="text/javascript" charset="utf8"
            src="{{URL::to('https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js')}}"></script>
    <script type="text/javascript" charset="utf8"
            src="{{URL::to('https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js')}}"></script>
    <script type="text/javascript" charset="utf8"
            src="{{URL::to('https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js')}}"></script>
    <script type="text/javascript" charset="utf8"
            src="{{URL::to('https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js')}}"></script>
    <script type="text/javascript" charset="utf8"
            src="{{URL::to('https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js')}}"></script>

    <script>
        $.noConflict();
        jQuery(document).ready(function ($) {
            $('#example').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'excel'
                ]
            });
        });
    </script>
@endsection

resources/views/users/user_profile.blade.php
@extends('layouts.user.details')
@section('names')
    {{$user->first_name  }} {{$user->second_name}}
@endsection
@section('details')
    <div class="row  user-header">
        <div class="col-lg-6">
            Profile
        </div>
        <div class="col-lg-6" style="text-align: right">
            @if(\App\Http\Traits\UniversalMethods::hasActiveLoan($user->id))
                <b style="color: #E55025">Active</b>
            @else
                @if($user->loans()->where('loan_status',4)->first() != null)
                    <td style="color: #E55025">Has a Bad Debt</td>
                @else
                    <td style="color: #012B43">Inactive</td>
                @endif
            @endif
        </div>
    </div>

    <div class="row user-content">
        <div class="col-lg-6">

            <ul>
                <li><b>Basic Details</b></li>
                <li>ID Number: {{$user->id_number}}</li>
                <li>Occupation: {{$user->occupation}}</li>
                <li>D.O.B: {{$user->date_of_birth}}</li>
                <li>Region: {{$user->region_name}}</li>
                <li>Country: {{$user->country}}</li>
            </ul>

        </div>
        <div class="col-lg-6">

            <ul>
                <li><b>Contact Details</b></li>
                <li>Phone Number: {{$user->phone_number}}</li>
                <li>Email Address: {{$user->email}}</li>
            </ul>

        </div>
    </div>

@endsection